boom! testing mysql-9.0.1 against beta for beta
boom! running: cargo +beta build --frozen
boom! creating container for: cargo +beta build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/beta/beta:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/beta/beta:/target:rw -e USER_ID=500 -e CMD=cargo +beta build --frozen cargobomb`
blam! e028b7c5a740254cdaf12713890d3239ae739dd60dc42638fd571784940e7205
boom! running `docker start -a e028b7c5a740254cdaf12713890d3239ae739dd60dc42638fd571784940e7205`
kablam!    Compiling mysql v9.0.1 (file:///source)
kablam!     Finished dev [unoptimized + debuginfo] target(s) in 12.62 secs
boom! running `docker rm -f e028b7c5a740254cdaf12713890d3239ae739dd60dc42638fd571784940e7205`
blam! e028b7c5a740254cdaf12713890d3239ae739dd60dc42638fd571784940e7205
boom! running: cargo +beta test --frozen --no-run
boom! creating container for: cargo +beta test --frozen --no-run
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/beta/beta:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/beta/beta:/target:rw -e USER_ID=500 -e CMD=cargo +beta test --frozen --no-run cargobomb`
blam! 471e64f0b6f0e027dc4e709e19034d65bce570b9bc4f6b62395d3b114cb6e819
boom! running `docker start -a 471e64f0b6f0e027dc4e709e19034d65bce570b9bc4f6b62395d3b114cb6e819`
kablam!    Compiling mysql v9.0.1 (file:///source)
kablam! warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
kablam!     --> src/conn/mod.rs:2371:17
kablam!      |
kablam! 2371 |             let mut opts = OptsBuilder::from_opts(get_opts());
kablam!      |                 ^^^^^^^^
kablam! 
kablam!     Finished dev [unoptimized + debuginfo] target(s) in 18.8 secs
boom! running `docker rm -f 471e64f0b6f0e027dc4e709e19034d65bce570b9bc4f6b62395d3b114cb6e819`
blam! 471e64f0b6f0e027dc4e709e19034d65bce570b9bc4f6b62395d3b114cb6e819
boom! running: cargo +beta test --frozen
boom! creating container for: cargo +beta test --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/beta/beta:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/beta/beta:/target:rw -e USER_ID=500 -e CMD=cargo +beta test --frozen cargobomb`
blam! 95d4055bf1008147b0d7296223b6fe4eac3388f05218210f9d1ce4e8ea8e0744
boom! running `docker start -a 95d4055bf1008147b0d7296223b6fe4eac3388f05218210f9d1ce4e8ea8e0744`
kablam!     Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
kablam!      Running /target/debug/deps/mysql-b52ead08bfc7aa76
blam! 
blam! running 72 tests
blam! test conn::opts::test::should_convert_url_into_opts ... ok
blam! test conn::opts::test::should_panic_on_invalid_url ... ok
blam! test conn::opts::test::should_panic_if_verify_peer_query_param_requires_feature ... ok
blam! test conn::opts::test::should_panic_on_invalid_scheme ... ok
blam! test conn::pool::test::pool::should_execute_statements_on_PooledConn ... FAILED
blam! test conn::pool::test::pool::should_execute_queryes_on_PooledConn ... FAILED
blam! test conn::pool::test::pool::should_execute_statements_on_Pool ... FAILED
blam! test conn::pool::test::pool::should_fix_connectivity_errors_on_prep_exec ... FAILED
blam! test conn::pool::test::pool::should_fix_connectivity_errors_on_start_transaction ... FAILED
blam! test conn::opts::test::should_panic_on_unknown_query_param ... ok
blam! test conn::pool::test::pool::should_start_transaction_on_PooledConn ... FAILED
blam! test conn::pool::test::pool::should_fix_connectivity_errors_on_prepare ... FAILED
blam! test conn::pool::test::pool::should_timeout_if_no_connections_available ... FAILED
blam! test conn::pool::test::pool::should_work_with_named_params ... FAILED
blam! test conn::pool::test::pool::should_start_transaction_on_Pool ... FAILED
blam! test conn::pool::test::pool::should_not_block_when_pool_capacity_goes_to_tls ... FAILED
blam! test conn::test::my_conn::should_connect_by_hostname ... FAILED
blam! test conn::test::my_conn::should_connect_via_socket_for_127_0_0_1 ... FAILED
blam! test conn::test::my_conn::should_connect_via_socket_localhost ... FAILED
blam! test conn::test::my_conn::should_connect ... FAILED
blam! test conn::test::my_conn::should_connect_with_database ... FAILED
blam! test conn::test::my_conn::should_execute_statements_and_parse_results ... FAILED
blam! test conn::test::my_conn::should_execute_queryes_and_parse_results ... FAILED
blam! test conn::test::my_conn::should_handle_LOCAL_INFILE_with_custom_handler ... FAILED
blam! test conn::test::my_conn::should_handle_LOCAL_INFILE ... FAILED
blam! test conn::test::my_conn::should_panic_on_named_param_redefinition ... ok
blam! test conn::test::my_conn::should_handle_multi_resultset ... FAILED
blam! test conn::test::my_conn::should_parse_column_from_payload ... ok
blam! test conn::test::my_conn::should_parse_large_binary_result ... FAILED
blam! test conn::test::my_conn::should_return_error_on_missing_named_parameter ... FAILED
blam! test conn::test::my_conn::should_parse_large_text_result ... FAILED
blam! test conn::test::my_conn::should_return_error_on_named_params_for_positional_statement ... FAILED
blam! test conn::test::my_conn::should_reset_connection ... FAILED
blam! test my_uuid::test::should_convert_bytes_to_uuid ... ok
blam! test my_uuid::test::should_convert_uuid_to_bytes ... ok
blam! test named_params::test::should_allow_numbers_in_param_name ... ok
blam! test named_params::test::should_parse_named_params ... ok
blam! test conn::test::my_conn::should_start_commit_and_rollback_transactions ... FAILED
blam! test conn::test::my_conn::should_work_with_named_params ... FAILED
blam! test named_params::test::special_characters_in_query ... ok
blam! test packet::test::should_parse_Error_packet ... ok
blam! test packet::test::should_parse_EOF_packet ... ok
blam! test parser::test::should_parse_column_definition ... ok
blam! test packet::test::should_parse_OK_packet ... ok
blam! test scramble::sha1::test::should_compute_sha1_hash ... ok
blam! test scramble::test::should_compute_scrambled_password ... ok
blam! test value::test::from_row::should_return_error_if_could_not_convert ... ok
blam! test value::test::from_row::should_convert_to_tuples ... ok
blam! test packet::test::should_parse_handshake_packet ... ok
blam! test value::test::from_value::should_convert_Bytes_to_Timespec ... ok
blam! test value::test::from_value::should_convert_Bytes_to_NaiveDate ... ok
blam! test value::test::from_value::should_convert_Value_to_NaiveDate ... ok
blam! test value::test::from_value::should_convert_Value_to_NaiveDateTime ... ok
blam! test value::test::from_value::should_convert_Value_to_NaiveTime ... ok
blam! test value::test::from_value::should_convert_signed_to_unsigned ... ok
blam! test value::test::from_value::should_convert_Bytes_to_time_Duration ... ok
blam! test value::test::from_value::should_not_convert_negative_to_unsigned ... ok
blam! test value::test::from_value::stored_and_retrieved_timestamp_should_match ... FAILED
blam! test value::test::into_str::should_convert_Bytes_to_mysql_string ... ok
blam! test value::test::into_str::should_convert_Date_to_mysql_string ... ok
blam! test value::test::from_value::stored_and_retrieved_datetime_should_match ... FAILED
blam! test value::test::into_str::should_convert_Float_to_mysql_string ... ok
blam! test value::test::into_str::should_convert_NULL_to_mysql_string ... ok
blam! test value::test::into_str::should_convert_Int_to_mysql_string ... ok
blam! test value::test::into_str::should_convert_UInt_to_mysql_string ... ok
blam! test value::test::into_str::should_escape_specials_while_converting_Bytes ... ok
blam! test value::test::into_str::should_use_hex_literals_for_binary_Bytes ... ok
blam! test value::test::to_value::should_convert_Time_to_Date ... ok
blam! test value::test::from_value::should_convert_Bytes_to_NaiveTime ... ok
blam! test value::test::into_str::should_convert_Time_to_mysql_string ... ok
blam! test value::test::to_value::should_convert_time_Duration_to_Time ... ok
blam! test value::test::from_value::should_convert_Bytes_to_NaiveDateTime ... ok
blam! 
blam! failures:
blam! 
blam! ---- conn::pool::test::pool::should_execute_statements_on_PooledConn stdout ----
blam! 	thread 'conn::pool::test::pool::should_execute_statements_on_PooledConn' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::pool::test::pool::should_execute_queryes_on_PooledConn stdout ----
blam! 	thread 'conn::pool::test::pool::should_execute_queryes_on_PooledConn' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::pool::test::pool::should_execute_statements_on_Pool stdout ----
blam! 	thread 'conn::pool::test::pool::should_execute_statements_on_Pool' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::pool::test::pool::should_fix_connectivity_errors_on_prep_exec stdout ----
blam! 	thread 'conn::pool::test::pool::should_fix_connectivity_errors_on_prep_exec' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::pool::test::pool::should_fix_connectivity_errors_on_start_transaction stdout ----
blam! 	thread 'conn::pool::test::pool::should_fix_connectivity_errors_on_start_transaction' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::pool::test::pool::should_start_transaction_on_PooledConn stdout ----
blam! 	thread 'conn::pool::test::pool::should_start_transaction_on_PooledConn' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::pool::test::pool::should_fix_connectivity_errors_on_prepare stdout ----
blam! 	thread 'conn::pool::test::pool::should_fix_connectivity_errors_on_prepare' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::pool::test::pool::should_timeout_if_no_connections_available stdout ----
blam! 	thread 'conn::pool::test::pool::should_timeout_if_no_connections_available' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::pool::test::pool::should_work_with_named_params stdout ----
blam! 	thread 'conn::pool::test::pool::should_work_with_named_params' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::pool::test::pool::should_start_transaction_on_Pool stdout ----
blam! 	thread 'conn::pool::test::pool::should_start_transaction_on_Pool' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::pool::test::pool::should_not_block_when_pool_capacity_goes_to_tls stdout ----
blam! 	thread 'conn::pool::test::pool::should_not_block_when_pool_capacity_goes_to_tls' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_connect_by_hostname stdout ----
blam! 	thread 'conn::test::my_conn::should_connect_by_hostname' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_connect_via_socket_for_127_0_0_1 stdout ----
blam! 	thread 'conn::test::my_conn::should_connect_via_socket_for_127_0_0_1' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_connect_via_socket_localhost stdout ----
blam! 	thread 'conn::test::my_conn::should_connect_via_socket_localhost' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_connect stdout ----
blam! 	thread 'conn::test::my_conn::should_connect' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_connect_with_database stdout ----
blam! 	thread 'conn::test::my_conn::should_connect_with_database' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_execute_statements_and_parse_results stdout ----
blam! 	thread 'conn::test::my_conn::should_execute_statements_and_parse_results' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_execute_queryes_and_parse_results stdout ----
blam! 	thread 'conn::test::my_conn::should_execute_queryes_and_parse_results' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_handle_LOCAL_INFILE_with_custom_handler stdout ----
blam! 	thread 'conn::test::my_conn::should_handle_LOCAL_INFILE_with_custom_handler' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_handle_LOCAL_INFILE stdout ----
blam! 	thread 'conn::test::my_conn::should_handle_LOCAL_INFILE' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_handle_multi_resultset stdout ----
blam! 	thread 'conn::test::my_conn::should_handle_multi_resultset' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_parse_large_binary_result stdout ----
blam! 	thread 'conn::test::my_conn::should_parse_large_binary_result' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_return_error_on_missing_named_parameter stdout ----
blam! 	thread 'conn::test::my_conn::should_return_error_on_missing_named_parameter' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_parse_large_text_result stdout ----
blam! 	thread 'conn::test::my_conn::should_parse_large_text_result' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_return_error_on_named_params_for_positional_statement stdout ----
blam! 	thread 'conn::test::my_conn::should_return_error_on_named_params_for_positional_statement' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_reset_connection stdout ----
blam! 	thread 'conn::test::my_conn::should_reset_connection' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_start_commit_and_rollback_transactions stdout ----
blam! 	thread 'conn::test::my_conn::should_start_commit_and_rollback_transactions' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- conn::test::my_conn::should_work_with_named_params stdout ----
blam! 	thread 'conn::test::my_conn::should_work_with_named_params' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `localhost:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- value::test::from_value::stored_and_retrieved_timestamp_should_match stdout ----
blam! 	thread 'value::test::from_value::stored_and_retrieved_timestamp_should_match' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! ---- value::test::from_value::stored_and_retrieved_datetime_should_match stdout ----
blam! 	thread 'value::test::from_value::stored_and_retrieved_datetime_should_match' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `127.0.0.1:3307': Connection refused (os error 111) }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
blam! 
blam! 
blam! failures:
blam!     conn::pool::test::pool::should_execute_queryes_on_PooledConn
blam!     conn::pool::test::pool::should_execute_statements_on_Pool
blam!     conn::pool::test::pool::should_execute_statements_on_PooledConn
blam!     conn::pool::test::pool::should_fix_connectivity_errors_on_prep_exec
blam!     conn::pool::test::pool::should_fix_connectivity_errors_on_prepare
blam!     conn::pool::test::pool::should_fix_connectivity_errors_on_start_transaction
blam!     conn::pool::test::pool::should_not_block_when_pool_capacity_goes_to_tls
blam!     conn::pool::test::pool::should_start_transaction_on_Pool
blam!     conn::pool::test::pool::should_start_transaction_on_PooledConn
blam!     conn::pool::test::pool::should_timeout_if_no_connections_available
blam!     conn::pool::test::pool::should_work_with_named_params
blam!     conn::test::my_conn::should_connect
blam!     conn::test::my_conn::should_connect_by_hostname
blam!     conn::test::my_conn::should_connect_via_socket_for_127_0_0_1
blam!     conn::test::my_conn::should_connect_via_socket_localhost
blam!     conn::test::my_conn::should_connect_with_database
blam!     conn::test::my_conn::should_execute_queryes_and_parse_results
blam!     conn::test::my_conn::should_execute_statements_and_parse_results
blam!     conn::test::my_conn::should_handle_LOCAL_INFILE
blam!     conn::test::my_conn::should_handle_LOCAL_INFILE_with_custom_handler
blam!     conn::test::my_conn::should_handle_multi_resultset
blam!     conn::test::my_conn::should_parse_large_binary_result
blam!     conn::test::my_conn::should_parse_large_text_result
blam!     conn::test::my_conn::should_reset_connection
blam!     conn::test::my_conn::should_return_error_on_missing_named_parameter
blam!     conn::test::my_conn::should_return_error_on_named_params_for_positional_statement
blam!     conn::test::my_conn::should_start_commit_and_rollback_transactions
blam!     conn::test::my_conn::should_work_with_named_params
blam!     value::test::from_value::stored_and_retrieved_datetime_should_match
blam!     value::test::from_value::stored_and_retrieved_timestamp_should_match
blam! 
blam! test result: FAILED. 42 passed; 30 failed; 0 ignored; 0 measured
blam! 
kablam! error: test failed
boom! running `docker rm -f 95d4055bf1008147b0d7296223b6fe4eac3388f05218210f9d1ce4e8ea8e0744`
blam! 95d4055bf1008147b0d7296223b6fe4eac3388f05218210f9d1ce4e8ea8e0744
